#! /bin/sh

sxhkd &

bspc monitor DP-0 -d web file code music 6 7
bspc monitor HDMI-0 -d term web-aux chat 9

bspc config border_width         0 
bspc config window_gap           7 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^5 
bspc rule -a Firefox desktop=^1 
bspc rule -a Genymotion desktop=^3
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Slack desktop=^3 focus=on
bspc rule -a jetbrains-phpstorm desktop=^7
bspc rule -a spotify desktop=^8
bspc rule -a mplayer2 state=floating
bspc rule -a Gedit state=floating
bspc rule -a Eog state=floating
bspc rule -a Nemo desktop=^6 focus=on
bspc rule -a File-roller state=floating
bspc rule -a Gnome-system-monitor state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
#bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa
bash ~/.screenlayout/dual.sh
xsetroot -cursor_name left_ptr
 
feh --bg-fill ~/wallpaper.jpeg 
compton --config ~/.config/compton/config -b
xrdb -merge ~/.Xdefaults

cadence-session-start --system-start
udiskie
dunst &
polybar top &
